Fix action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -39,9 +39,11 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - run: cp ${{ github.action_path }}/coverage_processor.py .
+    - id: copy-coverage-processor
+      run: cp ${{ github.action_path }}/coverage_processor.py .
       shell: bash
-    - run: |
+    - id: run-tests
+      run: |
         ${{ github.action_path }}/entrypoint.sh \
         "${{ inputs.package-manager }}" \
         "${{ inputs.requirements-file }}" \
@@ -50,39 +52,18 @@ runs:
         "${{ inputs.cov-omit-list }}" \
         ${{ inputs.cov-threshold-single }} \
         ${{ inputs.cov-threshold-total }} \
-      id: coverage
       shell: bash
-#    - uses: peter-evans/find-comment@v1
-#      id: fc
-#      with:
-#        issue-number: ${{ github.event.pull_request.number }}
-#        comment-author: 'github-actions[bot]'
-#        direction: last
-#    - run: echo "SHORT_SHA=`echo ${{github.event.after}} | cut -c1-7`" >> $GITHUB_ENV
-#      shell: bash
-#    - run: echo "COMMIT_URL=`echo https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/commits/${{ github.event.after }}`"
-#      shell: bash
-#    - uses: peter-evans/create-or-update-comment@v1
-#      with:
-#        issue-number: ${{ github.event.pull_request.number }}
-#        comment-id: ${{ steps.fc.outputs.comment-id }}
-#        body: |
-#          ## Tests coverage table for [${{ env.SHORT_SHA }}](${{ env.COMMIT_URL }}) commit.
-#          ${{ steps.pytester-cov.outputs.output-table }}
-#        edit-mode: replace
-    - run: |
-      if echo ${{ steps.coverage.outputs.cov-threshold-single-fail }} | grep -c "true"
+    - id: check-threashold
+      run: |
+      if [ -z "${{ steps.coverage.outputs.cov-threshold-single-fail }}" ]
       then
         echo "cov single fail ${{ steps.coverage.outputs.cov-threshold-single-fail }}"
         exit 1
+      elif [ -z "${{ steps.coverage.outputs.cov-threshold-total-fail }}" ]
+      then
+        echo "cov single fail ${{ steps.coverage.outputs.cov-threshold-total-fail }}"
+        exit 1
       fi
-      shell: bash
-    - run: |
-        if echo ${{ steps.coverage.outputs.cov-threshold-total-fail }} | grep -c "true"
-        then
-          echo "cov single fail ${{ steps.coverage.outputs.cov-threshold-total-fail }}"
-          exit 1
-        fi
       shell: bash
     - uses: peter-evans/commit-comment@v1
       with:
