Fix action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -71,14 +71,18 @@ runs:
 #          ${{ steps.pytester-cov.outputs.output-table }}
 #        edit-mode: replace
     - run: |
-      [[ ${{ steps.coverage.outputs.cov-threshold-single-fail == 'true' }} ]] && \
-      echo "cov single fail ${{ steps.coverage.outputs.cov-threshold-single-fail }}" && \
-      exit 1
+      if echo ${{ steps.coverage.outputs.cov-threshold-single-fail }} | grep -c "true"
+      then
+        echo "cov single fail ${{ steps.coverage.outputs.cov-threshold-single-fail }}" && \
+        exit 1
+      fi
       shell: bash
     - run: |
-        [[ ${{ steps.coverage.outputs.cov-threshold-total-fail == 'true' }} ]] && \
-        echo "cov total fail ${{ steps.coverage.outputs.cov-threshold-total-fail }}" && \
-        exit 1
+        if echo ${{ steps.coverage.outputs.cov-threshold-total-fail }} | grep -c "true"
+        then
+          echo "cov single fail ${{ steps.coverage.outputs.cov-threshold-total-fail }}" && \
+          exit 1
+        fi
       shell: bash
     - uses: peter-evans/commit-comment@v1
       with:
